language: objective-c
osx_image: xcode9.2

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=SnipsPlatformDemo.xcworkspace
  - IOS_FRAMEWORK_SCHEME=SnipsPlatform
  matrix:
    - DESTINATION="OS=11.2,name=iPhone X" SCHEME="$IOS_FRAMEWORK_SCHEME" POD_LINT="YES"

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" test | xcpretty;
  - if [ $POD_LINT == "YES" ]; then
      sed -i.bk "s:\${SRCROOT}/SnipsPlatform:$(pwd):g" SnipsPlatform.podspec && pod lib lint --verbose;
    fi
